### ISSUE TITLE
Variant scoring

### ISSUE THREAD

**Issue by bovagner** [naumanjaved/EpiBERT#2]
Hello

What an interesting model you've created.

I tried running the tutorial notebooks and encountered a few issues, some of which I've not been able to overcome.

0) I had to put the notebooks in the EpiBERT install dir in order to be able to import the modules.

1) Apparently the bioconda version of `meme` has an issue that causes `sea` to fail on the example dataset (at least it did for me). This could be useful information for others.

2) Judging from the code, the `atac_file` in caqTL_predict.ipynb should be a bedgraph file, which is not created in data_processing.ipynb. I created this manually using:

```
bamid='ENCFF534DCE'
samtools sort -@ 8 -n ${bamid}.bam -o ${bamid}.namesorted.bam
bedtools bamtobed -i ${bamid}.namesorted.bam -bedpe | awk '$1 == $4' | awk '$8 >= 20' | awk -v OFS="\t" '{if($9 == "+"){print $1,$2+4,$6-5}else if($9=="-"){print $1,$5+4,$3-5}}' | awk -v OFS="\t" '{if($3<$2){print $1,$3,$2}else if($3>$2){print $1,$2,$3}}' | awk '$3-$2 > 0' | awk '$2 > 0' | sort -k1,1 -k2,2n > ${bamid}.bed
scale_factor_inv=$(cat ${bamid}.bed | wc -l | awk '{print 1000000 / $0}')
bedtools genomecov -i ${bamid}.bed -g $chrom_sizes_file -bg -scale ${scale_factor_inv} | sort -k1,1 -k2,2n -k3,3n > ${bamid}.bedgraph
bgzip -i ${bamid}.bedgraph
tabix -0 -p bed ${bamid}.bedgraph.gz
```

Tabix indexing also seems to be mandatory.
Would this be the correct way of creating the `atac_file`?

3) The `return_inputs_caqtl_score` function also need to receive an `interval` as the first input argument. It looks like the interval is automatically resized, so I just created a short interval around the variant:

`interval = 'chr12:9764948-9764949'`

4) When doing the variant scoring by running

```
with tf.device('/GPU:0'): # run on GPU 
    output,output_mut,caqtl_score = genformer.ca_qtl_score(inputs,inputs_mut)
```

I get a shape error, namely:

```
ValueError: Exception encountered when calling layer 'conv_block' (type Sequential).

In this `tf.Variable` creation, the initial value's shape ((5, 640, 640)) is not compatible with the explicitly supplied `shape` argument ((5, 640, 768)).

Call arguments received by layer 'conv_block' (type Sequential):
  • inputs=tf.Tensor(shape=(1, 65536, 640), dtype=bfloat16)
  • training=False
  • mask=None
```

Do you know what could be the issue here?

**Comment by naumanjaved** [comment]
Hello! 

Thanks for using the model and for catching these errors. 

1. I have corrected the import paths in the caqTL_predict example notebook so you should be able to run them without moving into the main installation directory. Some of the function/model names have also been updated (removed references to the old model name genformer) 
2. The file is indeed a bedgraph file (just without the bedGraph suffix) and should be tabix indexed.
3-5. I have uploaded a refactored version of the interval_and_plotting_utilities.py file where the inputs to the return_inputs_caqtl_score function have been corrected. Some of the function names have also been updated so please pull the new files. I have also uploaded an updated version of the main model file ( epibert_atac_pretrain.py) which now has the correct default number of filters for the convolutional sequence tower and should resolve the shape error you are getting. 

Please let me know if you have ongoing issues. I will soon be adding an example notebook for the gradient analysis.

**Comment by bovagner** [comment]
Thank you for the quick update.

I still have a few issues. One is with regards to the input `atac_file`. If I try to use the K562.bed.gz file created in data_processing.ipynb I run into the following:

1) The file is not coordinate sorted, so I cannot index it with tabix.

2) If I coordinate sort and use it as input, I get the following error when trying to run `return_inputs_caqtl_score`:

```
ValueError: Length mismatch: Expected axis has 3 elements, new values have 4 elements
```

3) If I use the bedgraph file that I created myself, I get a new shape error when running `ca_qtl_score`:

```
ValueError: Input 0 of layer "dense_7" is incompatible with the layer: expected axis -1 of input shape to have value 693, but received input with shape (1, 1, 374)
```

This shape error seems to be related to how the weights are imported, since I do not get it if I just apply a model without weights imported, i.e.:

```
model3 = epibert.epibert()
with tf.device('/GPU:0'): # run on GPU
    model3.predict_on_batch(inputs[0])
```

Looking forward to the additional example notebooks.

NB: You do `import src.models.epibert_atac_pretrain as epibert`, but then later overwrite the import with `epibert = utils.EpiBERT_model_nostrat(model1,model2,checkpoint1_path, checkpoint2_path)`, which potentially could lead to some confusion.

**Comment by naumanjaved** [comment]
Hi,

Sorry for the ongoing issues and thanks for your patience. 

1. The notebook has been corrected to include all commands to create the input bedgraph file. 
2. It looks like the uploaded motif file was incomplete (the SEA call may have terminated prematurely and only included 374 motif models). I've added a full version with all 693 motifs. 
3. I've corrected the function names to avoid the collision as you pointed out.

Hoping that this corrects the errors - please let me know if there are ongoing issues.

**Comment by bovagner** [comment]
Thank you for the update. The package does run without error now on the example data, which is very nice. However, I do get a different caqtl_score, -28.0 as opposed to -8.0. Likewise for the other variants.

I was wondering if it's intentional that you shift the fragment ends twice in the data processing notebook?

**Comment by naumanmjaved** [comment]
Hi,

Very sorry for the late reply. Thanks for pointing out the double shift - have corrected the analysis [notebook](https://github.com/naumanjaved/EpiBERT/blob/1b24e2971e0b2ffded1d8e577d28e282eeb23a27/example_usage/data_processing.ipynb#L151C2-L152C51). With this correction, I get a caqtl score of -36.0 (see updated caqtl notebook). Will have to dig into the reason for this discrepancy further. 

Nauman
